name: 'Execute'
inputs:
  token:
    default: ${{ github.token }}
  repository:
    default: ${{ github.repository }}
  workflow:
    default: ${{ github.workflow }}
  branch:
    default: ${{ github.ref_name }}
  inputs:
    defaults: "{}"
  run_ids:
    default: "{}"
  wait:
    default: false
outputs:
  run_id:
    description: "Triggered workflow run id"
  run_ids:
    description: "Waited workflow run ids"
runs:
  using: 'node20'
  main: 'execute.js'
